title: Zubeiru Bukari
logo: Image.png
description: A Data Analyst with about 4 years of experience in Report Automation using Advanced Excel, Data Manipulation, and Interogation on SQL and Business Intelligence Report on Power BI. I excel in working with diverse data sources and transforming complex datasets into actionable insights that support informed decision-making.
# show_downloads: true
# google_analytics:
theme: jekyll-theme-minimal
